/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutriIndexRouteImport } from './routes/nutri/index'

const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutriIndexRoute = NutriIndexRouteImport.update({
  id: '/nutri/',
  path: '/nutri/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/treino': typeof TreinoRoute
  '/nutri/': typeof NutriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/treino': typeof TreinoRoute
  '/nutri': typeof NutriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/treino': typeof TreinoRoute
  '/nutri/': typeof NutriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conquistas'
    | '/dieta'
    | '/evolucao'
    | '/login'
    | '/treino'
    | '/nutri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conquistas'
    | '/dieta'
    | '/evolucao'
    | '/login'
    | '/treino'
    | '/nutri'
  id:
    | '__root__'
    | '/'
    | '/conquistas'
    | '/dieta'
    | '/evolucao'
    | '/login'
    | '/treino'
    | '/nutri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConquistasRoute: typeof ConquistasRoute
  DietaRoute: typeof DietaRoute
  EvolucaoRoute: typeof EvolucaoRoute
  LoginRoute: typeof LoginRoute
  TreinoRoute: typeof TreinoRoute
  NutriIndexRoute: typeof NutriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutri/': {
      id: '/nutri/'
      path: '/nutri'
      fullPath: '/nutri/'
      preLoaderRoute: typeof NutriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConquistasRoute: ConquistasRoute,
  DietaRoute: DietaRoute,
  EvolucaoRoute: EvolucaoRoute,
  LoginRoute: LoginRoute,
  TreinoRoute: TreinoRoute,
  NutriIndexRoute: NutriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
